# Generated by Django 5.1.7 on 2025-06-15 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DispatchRider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=11, unique=True)),
                (
                    "rider_image",
                    models.FileField(
                        default="default_carousel.jpg",
                        upload_to="images/rider_profiles",
                    ),
                ),
                (
                    "rider_location",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
    ]
