# Generated by Django 5.1.7 on 2025-06-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Delivery", "0002_dispatchrider_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchrider",
            name="dispatch_type",
            field=models.CharField(
                choices=[
                    ("Estate", "Estate"),
                    ("Market", "Market"),
                    ("Restaurant", "Restaurant"),
                ],
                default="Estate",
                max_length=150,
            ),
            preserve_default=False,
        ),
    ]
