# Generated by Django 5.1.7 on 2025-06-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Delivery", "0003_dispatchrider_dispatch_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchrider",
            name="dispatch_type",
            field=models.CharField(
                choices=[
                    ("Estate", "Estate"),
                    ("Market", "Market"),
                    ("Restaurant", "Restaurant"),
                    ("HomeAppliance", "HomeAppliance"),
                ],
                max_length=150,
            ),
        ),
    ]
