# Generated by Django 5.1.7 on 2025-05-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=100)),
                ("LGA", models.CharField(max_length=100)),
                ("District", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "img_logo",
                    models.FileField(
                        default="shop-default.jpg", upload_to="images/shop"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("SHOP", "SHOP"), ("VENDOR", "VENDOR")], max_length=50
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Estates.estate",
                    ),
                ),
            ],
        ),
    ]
