# Generated by Django 5.1.7 on 2025-05-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="img_logo",
            field=models.FileField(
                default="shop-default.jpg", null=True, upload_to="images/shop"
            ),
        ),
    ]
