# Generated by Django 5.1.7 on 2025-05-08 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Estates", "0002_alter_shop_img_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estate", old_name="District", new_name="district",
        ),
    ]
