# Generated by Django 5.1.7 on 2025-05-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estates", "0003_rename_district_estate_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
