# Generated by Django 5.1.7 on 2025-03-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advert_title",
                    models.CharField(default="no advert title", max_length=100),
                ),
                (
                    "advert_text",
                    models.CharField(default="no advert text", max_length=250),
                ),
                (
                    "advert_location",
                    models.CharField(
                        choices=[
                            ("Nav_advert", "Nav_advert"),
                            ("CAROUSEL", "CAROUSEL"),
                            ("sec2_advert", "sec2_advert"),
                            ("sec3_advert", "sec3_advert"),
                            ("sec4_advert", "sec4_advert"),
                            ("whats-hot_advert", "whats-hot_advert"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "advert_img",
                    models.FileField(
                        default="default_carousel.jpg", upload_to="images/advert"
                    ),
                ),
                ("advert_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
