# Generated by Django 5.1.7 on 2025-04-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_homeappliances_newsletters_newslettersubscribers_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="advertisement", name="advert_location",),
        migrations.RemoveField(model_name="advertisement", name="advert_text",),
    ]
