# Generated by Django 5.1.7 on 2025-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_remove_advertisement_advert_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homeappliances",
            old_name="appliance_price",
            new_name="current_price",
        ),
        migrations.AddField(
            model_name="homeappliances",
            name="old_price",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
