# Generated by Django 5.1.7 on 2025-04-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_rename_appliance_price_homeappliances_current_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeappliances",
            name="appliance_image",
            field=models.FileField(default="default.jpg", upload_to="images/appliance"),
        ),
    ]
