# Generated by Django 5.1.7 on 2025-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0005_alter_homeappliances_appliance_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="utilitypayment", name="payment_url",),
        migrations.AddField(
            model_name="utilitypayment",
            name="utility_code",
            field=models.CharField(default="no code", max_length=100),
        ),
    ]
