# Generated by Django 5.1.7 on 2025-05-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0006_remove_utilitypayment_payment_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homeappliances",
            old_name="appliance_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="homeappliances", old_name="appliance_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="homeappliances", old_name="current_price", new_name="price",
        ),
        migrations.RenameField(
            model_name="homeappliances",
            old_name="appliance_image",
            new_name="product_img",
        ),
    ]
