# Generated by Django 5.1.7 on 2025-05-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0009_alter_homeappliances_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeappliances",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
