# Generated by Django 5.1.7 on 2025-05-08 01:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0001_initial"),
        ("Estates", "0003_rename_district_estate_district"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavouriteMarketShops", new_name="FavouriteEstateShops",
        ),
    ]
