# Generated by Django 5.1.7 on 2025-05-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0003_cart_cartitems"),
        ("Home", "0006_remove_utilitypayment_payment_url_and_more"),
        ("Products", "0004_alter_product_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="home_appliance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Home.homeappliances",
            ),
        ),
        migrations.AlterField(
            model_name="cartitems",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.product",
            ),
        ),
    ]
