# Generated by Django 5.1.7 on 2025-05-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0005_alter_favouriteestateshops_shop"),
        ("Estates", "0004_alter_shop_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favouriteestateshops",
            name="shop",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Estates.shop"
            ),
        ),
    ]
