# Generated by Django 5.1.7 on 2025-05-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0007_alter_favouriteestateshops_user_and_more"),
        ("Estates", "0004_alter_shop_name"),
        ("Products", "0004_alter_product_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favouriteestateshops",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Estates.shop"
            ),
        ),
        migrations.AlterField(
            model_name="favouriteproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Products.product"
            ),
        ),
    ]
