# Generated by Django 5.1.7 on 2025-05-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0008_alter_favouriteestateshops_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart", name="date", field=models.DateTimeField(auto_now=True),
        ),
    ]
