# Generated by Django 5.1.7 on 2025-06-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0009_alter_cart_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="payer_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
