# Generated by Django 5.1.7 on 2025-06-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0010_cart_payer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
