# Generated by Django 5.1.7 on 2025-06-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0011_alter_cart_transaction_id"),
        ("Delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cart",
            name="dispatch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Delivery.dispatchrider",
            ),
        ),
    ]
