# Generated by Django 5.1.7 on 2025-06-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0012_cart_delivered_cart_dispatch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="dispatch", new_name="dispatch_rider",
        ),
    ]
