# Generated by Django 5.1.7 on 2025-06-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0013_rename_dispatch_cart_dispatch_rider"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="delivery_address",
            field=models.CharField(
                default="no 54 temporary address, Abuja Nigeria", max_length=500
            ),
            preserve_default=False,
        ),
    ]
