# Generated by Django 5.1.7 on 2025-06-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0015_producttype"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="delivered",),
        migrations.RemoveField(model_name="cart", name="dispatch_rider",),
    ]
