# Generated by Django 5.1.7 on 2025-06-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0016_remove_cart_delivered_remove_cart_dispatch_rider"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="delivery_completed",
            field=models.BooleanField(default=False),
        ),
    ]
