# Generated by Django 5.1.7 on 2025-06-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0017_cart_delivery_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="product_type",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
