# Generated by Django 5.1.7 on 2025-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cart", "0018_alter_producttype_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartitems",
            name="received",
            field=models.BooleanField(default=False),
        ),
    ]
