# Generated by Django 5.1.7 on 2025-04-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomUser",),
    ]
