# Generated by Django 5.1.7 on 2025-05-05 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Estates", "0002_alter_shop_img_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.CharField(max_length=300)),
                ("price", models.CharField(max_length=200)),
                (
                    "product_img",
                    models.FileField(
                        default="product-default.jpg", upload_to="images/product"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Estates.shop",
                    ),
                ),
            ],
        ),
    ]
