# Generated by Django 5.1.7 on 2025-05-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_img",
            field=models.FileField(
                blank=True,
                default="product-default.jpg",
                null=True,
                upload_to="images/product",
            ),
        ),
    ]
