# Generated by Django 5.1.7 on 2025-05-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0002_alter_product_description_alter_product_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_category",
            field=models.CharField(default="others", max_length=200),
        ),
    ]
