# Generated by Django 5.1.7 on 2025-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0003_product_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(blank=True, default="others", max_length=200),
        ),
    ]
